apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-project-docs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "template-project-docs.name" . }}
    helm.sh/chart: {{ include "template-project-docs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "template-project-docs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "template-project-docs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.image.secretName }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
            - configMapRef:
                name: {{ include "template-project-docs.name" . }}-config
            - secretRef:
                name: {{ include "template-project-docs.name" . }}-password
          env:
            - name: INGRESS_HOST
              value: {{ include "template-project-docs.host" . }}
            - name: PROTOCOLS
              value: {{ include "template-project-docs.protocols" . }}
            - name: MESSAGE_PROCESSOR_URL
              value: {{ .Values.messageProcessorUrl }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
