{{- if .Values.configMap.create }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "template-project-docs.name" . }}-password
    labels:
        "app.kubernetes.io/name": {{ include "template-project-docs.name" . }}
        "app.kubernetes.io/instance": {{ include "template-project-docs.name" . }}
type: Opaque
stringData:
    GRAPH_API_APP_SECRET: {{ .Values.configMap.appSecret | quote }}
{{- end }}
