# Default values for template-project-docs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configMap:
  create: true
  appSecret: "5pM19US:RsQ]t0MBEu/oLLg@8ak5?r0Z"
  mailboxes: "sean@thesundbergs.net"
  tenantId: "5c463f99-c85e-4d1e-8f20-1ef3d232a71c"
  appId: "2b2d470f-17f4-484d-b185-26d0969818b6"
  clientState: "12345"
  autoSubscribe: "false"

messageProcessorUrl: "message-processor:80"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 80

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  #  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""
